### ISSUE TITLE
point TTS to vxml document

### ISSUE THREAD

**Issue by taymoork2** [CalvertYang/simple-nexmo#7]
Is there a way to have the 'sendTTSMessage' api point a .vxml url?

**Comment by CalvertYang** [comment]
@taymoork2
Text-To-Speech API didn't support VoiceXML.
You can use VoiceXML via the Call API in Voice API, but this package didn't support this feature yet, I'll try to add this feature soon.

**Comment by CalvertYang** [comment]
VoiceXML is now supported.
